ProyectoXalli_Gentella/Controllers/Catalogos/CategoriasProductoController.cs
using ProyectoXalli_Gentella.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ProyectoXalli_Gentella.Controllers
{
    public class CategoriasProductoController : Controller
    {
        private DBControl db = new DBControl();
        private bool completado = false;
        private string mensaje = "";

        // GET: CategoriasProducto
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// RECUPERA DATOS PARA LLENAR LA TABLA CATEGORIAS A TRAVES DE JSON
        /// </summary>
        /// <returns></returns>
        public async Task<JsonResult> GetData()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var categorias = await db.CategoriasProducto.Where(c => c.EstadoCategoria == true).ToListAsync();

            return Json(new { data = categorias }, JsonRequestBehavior.AllowGet);
        }

        // GET: CategoriasProducto/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriaProducto categorias = await db.CategoriasProducto.FindAsync(id);
            if (categorias == null)
            {
                return HttpNotFound();
            }
            return View(categorias);
        }

        // GET: CategoriasProducto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoriasProducto/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,CodigoCategoria,DescripcionCategoria,EstadoCategoria")] CategoriaProducto CategoriaProducto)
        {
            //BUSCAR QUE EXISTA UNA CATEGORIA CON ESA DESCRIPCION
            CategoriaProducto bod = db.CategoriasProducto.DefaultIfEmpty(null).FirstOrDefault(b => b.DescripcionCategoria.ToUpper().Trim() == CategoriaProducto.DescripcionCategoria.ToUpper().Trim());

            //SI EXISTE INGRESADO UNA CATEGORIA CON LA DESCRIPCION
            if (bod != null)
            {
                ModelState.AddModelError("DescripcionCategoria", "Utilice otro nombre");
                mensaje = "La descripción ya se encuentra registrada";
                return Json(new { success = completado, message = mensaje }, JsonRequestBehavior.AllowGet);
            }

            using (var transact = db.Database.BeginTransaction())
            {
                try
                {
                    //ESTADO DE LA CATEGORIA CUANDO SE CREA SIEMPRE ES TRUE
                    CategoriaProducto.EstadoCategoria = true;
                    if (ModelState.IsValid)
                    {
                        db.CategoriasProducto.Add(CategoriaProducto);
                        completado = await db.SaveChangesAsync() > 0 ? true : false;
                        mensaje = completado ? "Almacenado correctamente" : "Error al almacenar";
                    }
                    transact.Commit();
                }
                catch (Exception)
                {
                    mensaje = "Error al almacenar";
                    transact.Rollback();
                }//FIN TRY-CATCH
            }//FIN USING

            return Json(new { success = completado, message = mensaje }, JsonRequestBehavior.AllowGet);
        }

        // GET: CategoriasProducto/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriaProducto CategoriaProducto = await db.CategoriasProducto.FindAsync(id);
            if (CategoriaProducto == null)
            {
                return HttpNotFound();
            }
            return View(CategoriaProducto);
        }

        // POST: CategoriasProducto/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,CodigoCategoria,DescripcionCategoria,EstadoCategoria")] CategoriaProducto CategoriaProducto)
        {
            //BUSCAR QUE EXISTA UNA CATEGORIA CON ESA DESCRIPCION
            CategoriaProducto bod = db.CategoriasProducto.DefaultIfEmpty(null).FirstOrDefault(b => b.DescripcionCategoria.ToUpper().Trim() == CategoriaProducto.DescripcionCategoria.ToUpper().Trim() && b.Id != CategoriaProducto.Id);

            //SI EXISTE INGRESADO UNA CATEGORIA CON LA DESCRIPCION
            if (bod != null)
            {
                ModelState.AddModelError("DescripcionCategoria", "Utilice otro nombre");
                mensaje = "La descripción ya se encuentra registrada";
                return Json(new { success = completado, message = mensaje }, JsonRequestBehavior.AllowGet);
            }

            using (var transact = db.Database.BeginTransaction())
            {

                try
                {
                    if (ModelState.IsValid)
                    {
                        db.Entry(CategoriaProducto).State = EntityState.Modified;
                        completado = await db.SaveChangesAsync() > 0 ? true : false;
                        mensaje = completado ? "Modificado correctamente" : "Error al modificar";
                    }

                    transact.Commit();
                }
                catch (Exception)
                {
                    mensaje = "Error al modificar";
                    transact.Rollback();
                }
            }//FIN USING

            return Json(new { success = completado, message = mensaje }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// RETORNA EL CODIGO AUTOMATICAMENTE A LA VISTA CREATE
        /// </summary>
        /// <returns></returns>
        public ActionResult SearchCode()
        {
            //BUSCAR EL VALOR MAXIMO DE LAS BODEGAS REGISTRADAS
            var code = db.CategoriasProducto.Max(x => x.CodigoCategoria.Trim());
            int valor;
            string num;

            //SI EXISTE ALGUN REGISTRO
            if (code != null)
            {
                //CONVERTIR EL CODIGO A ENTERO
                valor = int.Parse(code);

                //SE COMIENZA A AGREGAR UN VALOR SECUENCIAL AL CODIGO ENCONTRADO
                if (valor <= 8)
                    num = "00" + (valor + 1);
                else
                if (valor >= 9 && valor < 100)
                    num = "0" + (valor + 1);
                else
                    num = (valor + 1).ToString();
            }
            else
                num = "001";//SE COMIENZA CON EL PRIMER CODIGO DEL REGISTRO

            return Json(num, JsonRequestBehavior.AllowGet);
        }

        // POST: CategoriasProducto/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var CategoriaProducto = db.CategoriasProducto.Find(id);
            //BUSCANDO QUE CATEGORIA PRODUCTOS REGISTRADAS CON SU ID
            Producto oProd = db.Productos.DefaultIfEmpty(null).FirstOrDefault(p => p.CategoriaId == CategoriaProducto.Id);

            using (var transact = db.Database.BeginTransaction())
            {
                try
                {
                    //SI NO SE ENCOTRARON PRODUCTOS EN LA CATEGORIA
                    if (oProd == null)
                    {
                        db.CategoriasProducto.Remove(CategoriaProducto);
                        completado = await db.SaveChangesAsync() > 0 ? true : false;
                        mensaje = completado ? "Eliminado correctamente" : "Error al eliminar";
                    }
                    else
                    {
                        mensaje = "Se encontraron productos registrados a esta categoría";
                    }

                    transact.Commit();
                }
                catch (Exception)
                {
                    mensaje = "Error al eliminar";
                    transact.Rollback();
                }//FIN TRY-CATCH
            }//FIN USING

            return Json(new { success = completado, message = mensaje }, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoXalli_Gentella/Views/CategoriasProducto/Create.cshtml
@model ProyectoXalli_Gentella.Models.CategoriaProducto

@{
    ViewBag.Title = "Creación";
    Layout = null;
}

<div class="row">
    <div class="x_content">

        @using (Html.BeginForm("Create", "CategoriasProducto", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" })) {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div data-parsley-validate class="form-horizontal form-label-left">
                <div class="form-group">
                    <div class="col-md-8 col-sm-8 col-xs-8">
                        @Html.Label("Código", htmlAttributes: new { @class = "col-md-4 col-sm-4 col-xs-4" })
                        @Html.EditorFor(model => model.CodigoCategoria, new { htmlAttributes = new { @class = "form-control col-md-2 col-sm-2 col-xs-2", @maxlength = 3, @id = "codigoCatProd", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.CodigoCategoria, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-3 col-sm-3 col-xs-3 col-md-offset-1">
                        @Html.Label("Activo", htmlAttributes: new { @class = "col-md-12 col-sm-12 col-xs-12" })
                        <label>
                            @Html.CheckBoxFor(model => model.EstadoCategoria, new { @class = "js-switch col-md-2 col-sm-2 col-xs-2", @readonly = "readonly", @checked = "checked" })
                            @Html.ValidationMessageFor(model => model.EstadoCategoria, "", new { @class = "text-danger" })
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        @Html.Label("Categoría", htmlAttributes: new { @class = "col-md-3 col-sm-3 col-xs-4" })
                        @Html.EditorFor(model => model.DescripcionCategoria, new { htmlAttributes = new { @class = "form-control", @maxlength = 50, @autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.DescripcionCategoria, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="ln_solid"></div>

                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-4">
                        <a onclick="CerrarModal()" class="btn btn-primary">Cerrar</a>
                        <button type="submit" class="btn btn-success">Guardar</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script>
    //INICIALIZADOR DE SWITCHERY
    $(document).ready(function () {
        var elem = document.querySelector('.js-switch');
        var init = new Switchery(elem);

        //CARGA EL CODIGO DE BODEGA
        $.ajax({
            type: "GET",
            url: "/CategoriasProducto/SearchCode",
            success: function (data) {
                $("#codigoCatProd").val(data);
            }
        });
    });
</script>

ProyectoXalli_Gentella/Views/CategoriasProducto/Details.cshtml
@model ProyectoXalli_Gentella.Models.CategoriaProducto

@{
    Layout = null;
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_content">
            <div data-parsley-validate class="form-horizontal form-label-left">

                    <div class="form-group">
                        @Html.Label("Código", htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                        <div class="control-label col-sm-2 col-xs-2">
                            @Html.DisplayFor(model => model.CodigoCategoria, new { htmlAttributes = new { @class = "col-md-7 col-xs-12" } })
                        </div>
                        <div class="control-label col-md-4 col-sm-4 col-xs-4">
                            <label>
                                @Html.CheckBoxFor(model => model.EstadoCategoria, new { @class = "js-switch", @onclick = "Check()", @disabled = "disabled" })
                                Estado
                            </label>
                        </div>
                    </div>

                <div class="form-group">
                    @Html.Label("Categoría", htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                    <div class="control-label col-md-3 col-sm-3 col-xs-3">
                        @Html.DisplayFor(model => model.DescripcionCategoria, new { htmlAttributes = new { @class = "col-md-7 col-xs-12" } })
                    </div>
                </div>

                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-6 col-md-offset-5">
                        <a onclick="CerrarModal()" class="btn btn-primary">Cerrar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    var elemen, init;

    $(document).ready(function () {

        elem = document.querySelector('.js-switch');
        init = new Switchery(elem);
    });

</script>

ProyectoXalli_Gentella/Views/CategoriasProducto/Edit.cshtml
@model ProyectoXalli_Gentella.Models.CategoriaProducto

@{
    ViewBag.Title = "Edición";
    Layout = null;
}

<div class="row">
    <div class="x_content">

        @using (Html.BeginForm("Edit", "CategoriasProducto", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" })) {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.CodigoCategoria)
            @Html.HiddenFor(model => model.Id)

            <div data-parsley-validate class="form-horizontal form-label-left">
                <div class="form-group">
                    <div class="col-md-8 col-sm-8 col-xs-8">
                        @Html.Label("Código", htmlAttributes: new { @class = "col-md-4 col-sm-4 col-xs-4" })
                        @Html.EditorFor(model => model.CodigoCategoria, new { htmlAttributes = new { @class = "form-control col-md-2 col-sm-2 col-xs-2", @disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.CodigoCategoria, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-3 col-sm-3 col-xs-3 col-md-offset-1">
                        @Html.Label("Activo", htmlAttributes: new { @class = "col-md-12 col-sm-12 col-xs-12" })
                        <label>
                            @Html.CheckBoxFor(model => model.EstadoCategoria, new { @class = "js-switch col-md-2 col-sm-2 col-xs-2", @onclick = "Check()" })
                            @Html.ValidationMessageFor(model => model.EstadoCategoria, "", new { @class = "text-danger" })
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        @Html.Label("Categoría", htmlAttributes: new { @class = "col-md-3 col-sm-3 col-xs-4" })
                        @Html.EditorFor(model => model.DescripcionCategoria, new { htmlAttributes = new { @class = "form-control", @maxlength = 50, @autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.DescripcionCategoria, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="ln_solid"></div>

                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-4">
                        <a onclick="CerrarModal()" class="btn btn-primary">Cerrar</a>
                        <button type="submit" class="btn btn-success">Guardar</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script>
    var elem, init;

    //INICIALIZAR EL CHECKBOX
    $(document).ready(function () {

        elem = document.querySelector('.js-switch');
        init = new Switchery(elem, { secondaryColor: '#CE2727' });
    });

    //CONFIRMACION DE ACTIVAR/DESACTIVAR
    function Check() {

        //DEPENDE DE SU ESTADO MANDAMOS UN ALERT
        if (!elem.checked) {

            swal({
                title: "¿Desea desactivar el registro?",
                icon: "warning",
                buttons: {
                    activar: {
                        text: "No",
                        value: "activar" //VALOR PARA UTILIZARLO EN EL SWITCH
                    },
                    desactivar: {
                        text: "Sí",
                        value: "desactivar" //VALOR PARA UTILIZARLO EN EL SWITCH
                    }
                }//FIN DE BUTTONS
            })//FIN DEL SWAL

                .then((value) => {
                    switch (value) {

                        case "activar":
                            //ACTIVAR EL CHKBOX
                            elem.click();
                            break;

                        case "desactivar":
                            //DESACTIVAR EL CHKBOX
                            swal.close();
                            break;

                        default:
                            {
                                swal.close();
                            }
                    }//FIN SWITCH
                });//FIN THEN
        }//FIN IF CHKBOX
    }//FIN FUNCION
</script>

ProyectoXalli_Gentella/Views/CategoriasProducto/Index.cshtml
@model ProyectoXalli_Gentella.Models.CategoriaProducto

@{
    ViewBag.Title = "Catálogo";
}

@Styles.Render("~/Content/datatableCSS")
<link href="~/Content/switchery.css" rel="stylesheet" />

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Lista de Categorías</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li class="pull-right">
                        <a onclick="CargarParcial('/CategoriasProducto/Create')"><i class="fa fa-plus"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="Table" class="table table-hover table-bordered" style="width:100% !important">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.CodigoCategoria)</th>
                            <th>@Html.DisplayNameFor(model => model.DescripcionCategoria)</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

@Html.Partial("_small-modal")

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/datatableJS")
    <script src="~/Scripts/Operaciones/ventanas.js"></script>
    <script src="~/Scripts/Catalogos/modelo.js"></script>

    <!--DATATABLE CATEGORIA-->
    <script>
        $("#small-modal").draggable({
            handle: ".modal-header"
        });

        //LLENANDO EL DATATABLE CRUD
        $(document).ready(function () {
            //DEFINIENDO EL DATATABLE
            $("#Table").DataTable({
                ajax: {
                    url: "/CategoriasProducto/GetData", //URL DE LA UBICACION DEL METODO
                    type: "GET", //TIPO DE ACCION
                    dataType: "JSON" //TIPO DE DATO A RECIBIR O ENVIAR
                },
                //DEFINIENDO LAS COLUMNAS A LLENAR
                columns: [
                    { data: "CodigoCategoria" },
                    { data: "DescripcionCategoria" },
                    {   //DEFINIENDO LOS BOTONES PARA EDITAR Y ELIMINAR POR MEDIO DE JS
                        data: "Id", "render": function (data) {
                            return "<a class='btn btn-success' onclick=CargarParcial('/CategoriasProducto/Edit/" + data + "')><i class='fa fa-pencil'></i></a>" +
                                "<a class='btn btn-danger' Style='margin-left: 3px' onclick=deleteAlert('/CategoriasProducto/Delete/'," + data + ")><i class='fa fa-trash'></i></a>"
                        }
                    }
                ],//FIN DE COLUMNAS
                //IDIOMA DE DATATABLE
                "language": {

                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",

                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                }//FIN IDIOMA DATATABLE
            });//FIN DECLARACION DEL DATATABLE
        });//FIN FUNCTION
    </script>
}