ProyectoXalli_Gentella/Controllers/Catalogos/CategoriasMenuController.cs
using ProyectoXalli_Gentella.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ProyectoXalli_Gentella.Controllers.Catalogos
{
    public class CategoriasMenuController : Controller
    {
        private DBControl db = new DBControl();
        private bool completado = false;
        private string mensaje = "";

        // GET: CategoriasMenu
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// RECUPERA DATOS PARA LLENAR LA TABLA CATEGORIAS A TRAVES DE JSON
        /// </summary>
        /// <returns></returns>
        public async Task<JsonResult> GetData()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var categorias = await db.CategoriasMenu.Where(c => c.EstadoCategoriaMenu == true).ToListAsync();

            return Json(new { data = categorias }, JsonRequestBehavior.AllowGet);
        }

        // GET: Categorias/Create
        public ActionResult Create()
        {
            ViewBag.BodegaId = new SelectList(db.Bodegas, "Id", "DescripcionBodega");

            return View();
        }

        // POST: Categorias/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,CodigoCategoriaMenu,DescripcionCategoriaMenu,EstadoCategoriaMenu,BodegaId")] CategoriaMenu CategoriaMenu)
        {
            //BUSCAR QUE EXISTA UNA CATEGORIA CON ESA DESCRIPCION
            CategoriaMenu bod = db.CategoriasMenu.DefaultIfEmpty(null).FirstOrDefault(b => b.DescripcionCategoriaMenu.ToUpper().Trim() == CategoriaMenu.DescripcionCategoriaMenu.ToUpper().Trim());

            //SI EXISTE INGRESADO UNA CATEGORIA CON LA DESCRIPCION
            if (bod != null) {
                ModelState.AddModelError("DescripcionCategoriaMenu", "Utilice otro nombre");
                mensaje = "La descripción ya se encuentra registrada";
                return Json(new { success = completado, message = mensaje }, JsonRequestBehavior.AllowGet);
            }

            using (var transact = db.Database.BeginTransaction()) {
                try {
                    //ESTADO DE LA CATEGORIA CUANDO SE CREA SIEMPRE ES TRUE
                    CategoriaMenu.EstadoCategoriaMenu = true;
                    if (ModelState.IsValid) {
                        db.CategoriasMenu.Add(CategoriaMenu);
                        completado = await db.SaveChangesAsync() > 0 ? true : false;
                        mensaje = completado ? "Almacenado correctamente" : "Error al almacenar";
                    }

                    transact.Commit();
                } catch (Exception) {
                    mensaje = "Error al almacenar";
                    transact.Rollback();
                }//FIN TRY-CATCH
            }//FIN USING
            return Json(new { success = completado, message = mensaje }, JsonRequestBehavior.AllowGet);
        }

        // GET: Categorias/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriaMenu CategoriaMenu = await db.CategoriasMenu.FindAsync(id);
            if (CategoriaMenu == null)
            {
                return HttpNotFound();
            }

            ViewBag.BodegaId = new SelectList(db.Bodegas, "Id", "DescripcionBodega", CategoriaMenu.BodegaId);

            return View(CategoriaMenu);
        }

        // POST: Categorias/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,CodigoCategoriaMenu,DescripcionCategoriaMenu,EstadoCategoriaMenu,BodegaId")] CategoriaMenu CategoriaMenu)
        {
            //BUSCAR QUE EXISTA UNA CATEGORIA CON ESA DESCRIPCION
            CategoriaMenu bod = db.CategoriasMenu.DefaultIfEmpty(null).FirstOrDefault(b => b.DescripcionCategoriaMenu.ToUpper().Trim() == CategoriaMenu.DescripcionCategoriaMenu.ToUpper().Trim()
            && b.Id != CategoriaMenu.Id);

            //SI EXISTE INGRESADO UNA CATEGORIA CON LA DESCRIPCION
            if (bod != null)
            {
                ModelState.AddModelError("DescripcionCategoriaMenu", "Utilice otro nombre");
                mensaje = "La descripción ya se encuentra registrada";
                return Json(new { success = completado, message = mensaje }, JsonRequestBehavior.AllowGet);
            }

            using (var transact = db.Database.BeginTransaction()) {
                try {
                    if (ModelState.IsValid) {
                        db.Entry(CategoriaMenu).State = EntityState.Modified;
                        completado = await db.SaveChangesAsync() > 0 ? true : false;
                        mensaje = completado ? "Modificado correctamente" : "Error al modificar";
                    }

                    transact.Commit();
                } catch (Exception) {
                    mensaje = "Error al modificar";
                    transact.Rollback();
                }//FIN TRY-CATCH
            }//FIN USING

            return Json(new { success = completado, message = mensaje }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// RETORNA EL CODIGO AUTOMATICAMENTE A LA VISTA CREATE
        /// </summary>
        /// <returns></returns>
        public ActionResult SearchCode()
        {
            //BUSCAR EL VALOR MAXIMO DE LAS BODEGAS REGISTRADAS
            var code = db.CategoriasMenu.Max(x => x.CodigoCategoriaMenu.Trim());
            int valor;
            string num;

            //SI EXISTE ALGUN REGISTRO
            if (code != null)
            {
                //CONVERTIR EL CODIGO A ENTERO
                valor = int.Parse(code);

                //SE COMIENZA A AGREGAR UN VALOR SECUENCIAL AL CODIGO ENCONTRADO
                if (valor <= 8)
                    num = "00" + (valor + 1);
                else
                if (valor >= 9 && valor < 100)
                    num = "0" + (valor + 1);
                else
                    num = (valor + 1).ToString();
            }
            else
                num = "001";//SE COMIENZA CON EL PRIMER CODIGO DEL REGISTRO

            return Json(num, JsonRequestBehavior.AllowGet);
        }

        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var categoriaMenu = db.CategoriasMenu.Find(id);
            //BUSCANDO QUE Categoria NO TENGA SALIDAS NI ENTRADAS REGISTRADAS CON SU ID
            Menu oMenu = db.Menus.DefaultIfEmpty(null).FirstOrDefault(p => p.CategoriaMenuId == categoriaMenu.Id);

            using (var transact = db.Database.BeginTransaction()) {
                try {
                    //SI NO SE ENCUENTRA ASOCIADO NINGUN PLATILLO AL ID
                    if (oMenu == null) {
                        db.CategoriasMenu.Remove(categoriaMenu);
                        completado = await db.SaveChangesAsync() > 0 ? true : false;
                        mensaje = completado ? "Eliminado correctamente" : "Error al eliminar";
                    } else {
                        mensaje = "Se encontraron platillos asociados a esta categoría";
                    }

                    transact.Commit();
                } catch (Exception) {
                    mensaje = "Error al eliminar";
                    transact.Rollback();
                }//FIN TRY-CATCH
            }//FIN USING

            return Json(new { success = completado, message = mensaje }, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoXalli_Gentella/Views/CategoriasMenu/Create.cshtml
@model ProyectoXalli_Gentella.Models.CategoriaMenu

@{
    Layout = null;
}

<div class="row">
    <div class="x_content">

        @using (Html.BeginForm("Create", "CategoriasMenu", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" })) {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div data-parsley-validate class="form-horizontal form-label-left">
                <div class="form-group">
                    <div class="col-md-8 col-sm-8 col-xs-8">
                        @Html.Label("Código", htmlAttributes: new { @class = "col-md-4 col-sm-4 col-xs-4" })
                        @Html.EditorFor(model => model.CodigoCategoriaMenu, new { htmlAttributes = new { @class = "form-control col-md-2 col-sm-2 col-xs-2", @maxlength = 3, @autocomplete = "off", @id = "codigoCatMenu", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.CodigoCategoriaMenu, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-3 col-sm-3 col-xs-3 col-md-offset-1">
                        @Html.Label("Activo", htmlAttributes: new { @class = "col-md-12 col-sm-12 col-xs-12" })
                        <label>
                            @Html.CheckBoxFor(model => model.EstadoCategoriaMenu, new { @class = "js-switch col-md-2 col-sm-2 col-xs-2", @readonly = "readonly", @checked = "checked" })
                            @Html.ValidationMessageFor(model => model.EstadoCategoriaMenu, "", new { @class = "text-danger" })
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.Label("Área", htmlAttributes: new { @class = "col-md-3 col-sm-3 col-xs-4" })
                        @Html.DropDownList("BodegaId", null, htmlAttributes: new { @class = "js-example-basic-single form-control", @Style = "width:100%", @id = "categoria" })
                        @Html.ValidationMessageFor(model => model.BodegaId, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.Label("Categoría", htmlAttributes: new { @class = "col-md-3 col-sm-3 col-xs-4" })
                        @Html.EditorFor(model => model.DescripcionCategoriaMenu, new { htmlAttributes = new { @class = "form-control", @maxlength = 50, @autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.DescripcionCategoriaMenu, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="ln_solid"></div>

                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-4">
                        <a onclick="CerrarModal()" class="btn btn-primary">Cerrar</a>
                        <button type="submit" class="btn btn-success">Guardar</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script>
    //INICIALIZAR EL SWITCHERY
    $(document).ready(function () {
        var elem = document.querySelector('.js-switch');
        var init = new Switchery(elem);

        //CARGA EL CODIGO DE CATEGORIA
        $.ajax({
            type: "GET",
            url: "/CategoriasMenu/SearchCode",
            success: function (data) {
                $("#codigoCatMenu").val(data);
            }
        });
    });

    //INICIALIZAR EL SELECT2
    $('.js-example-basic-single').select2({
        //MODIFICAR LAS FRASES DEFAULT DE SELECT2
        language: {

            noResults: function () {

                return "No hay resultado";
            },
            searching: function () {

                return "Buscando...";
            }
        }
    });
</script>

ProyectoXalli_Gentella/Views/CategoriasMenu/Edit.cshtml
@model ProyectoXalli_Gentella.Models.CategoriaMenu

@{
    Layout = null;
}


<div class="row">
    <div class="x_content">

        @using (Html.BeginForm("Edit", "CategoriasMenu", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" })) {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.CodigoCategoriaMenu)


            <div data-parsley-validate class="form-horizontal form-label-left">
                <div class="form-group">
                    <div class="col-md-8 col-sm-8 col-xs-8">
                        @Html.Label("Código", htmlAttributes: new { @class = "col-md-4 col-sm-4 col-xs-4" })
                        @Html.EditorFor(model => model.CodigoCategoriaMenu, new { htmlAttributes = new { @class = "form-control col-md-2 col-sm-2 col-xs-2", @disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.CodigoCategoriaMenu, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-3 col-sm-3 col-xs-3 col-md-offset-1">
                        @Html.Label("Activo", htmlAttributes: new { @class = "col-md-12 col-sm-12 col-xs-12" })
                        <label>
                            @Html.CheckBoxFor(model => model.EstadoCategoriaMenu, new { @class = "js-switch col-md-2 col-sm-2 col-xs-2", @onclick = "Check()" })
                            @Html.ValidationMessageFor(model => model.EstadoCategoriaMenu, "", new { @class = "text-danger" })
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.Label("Área", htmlAttributes: new { @class = "col-md-3 col-sm-3 col-xs-4" })
                        @Html.DropDownList("BodegaId", null, htmlAttributes: new { @class = "js-example-basic-single form-control", @Style = "width:100%", @id = "categoria" })
                        @Html.ValidationMessageFor(model => model.BodegaId, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.Label("Categoría", htmlAttributes: new { @class = "col-md-3 col-sm-3 col-xs-4" })
                        @Html.EditorFor(model => model.DescripcionCategoriaMenu, new { htmlAttributes = new { @class = "form-control", @maxlength = 50, @autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.DescripcionCategoriaMenu, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="ln_solid"></div>

                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-4">
                        <a onclick="CerrarModal()" class="btn btn-primary">Cerrar</a>
                        <button type="submit" class="btn btn-success">Guardar</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script>
    var elem, init;

    //INICIALIZAR EL CHECKBOX
    $(document).ready(function () {

        elem = document.querySelector('.js-switch');
        init = new Switchery(elem, { secondaryColor: '#CE2727' });
    });

    //CONFIRMACION DE ACTIVAR/DESACTIVAR
    function Check() {

        //DEPENDE DE SU ESTADO MANDAMOS UN ALERT
        if (!elem.checked) {

            swal({
                title: "¿Desea desactivar el registro?",
                icon: "warning",
                buttons: {
                    activar: {
                        text: "No",
                        value: "activar" //VALOR PARA UTILIZARLO EN EL SWITCH
                    },
                    desactivar: {
                        text: "Sí",
                        value: "desactivar" //VALOR PARA UTILIZARLO EN EL SWITCH
                    }
                }//FIN DE BUTTONS
            })//FIN DEL SWAL

                .then((value) => {
                    switch (value) {

                        case "activar":
                            //ACTIVAR EL CHKBOX
                            elem.click();
                            break;

                        case "desactivar":
                            //DESACTIVAR EL CHKBOX
                            swal.close();
                            break;

                        default:
                            {
                                swal.close();
                            }
                    }//FIN SWITCH
                });//FIN THEN
        }//FIN IF CHKBOX
    }//FIN FUNCION

    //INICIALIZAR EL SELECT2
    $('.js-example-basic-single').select2({
        //MODIFICAR LAS FRASES DEFAULT DE SELECT2
        language: {

            noResults: function () {

                return "No hay resultado";
            },
            searching: function () {

                return "Buscando...";
            }
        }
    });
</script>

ProyectoXalli_Gentella/Views/CategoriasMenu/Index.cshtml
@model ProyectoXalli_Gentella.Models.CategoriaMenu

@{
    ViewBag.Title = "Catálogo";
}

@Styles.Render("~/Content/datatableCSS")
<link href="~/Content/switchery.css" rel="stylesheet" />
<link href="~/Content/select2.min.css" rel="stylesheet" />

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Lista de Categorías</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li class="pull-right">
                        <a onclick="CargarParcial('/CategoriasMenu/Create')"><i class="fa fa-plus"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="Table" class="table table-hover table-bordered" style="width:100% !important">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.CodigoCategoriaMenu)</th>
                            <th>@Html.DisplayNameFor(model => model.DescripcionCategoriaMenu)</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

@Html.Partial("_small-modal")

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/datatableJS")
    <script src="~/Scripts/Operaciones/ventanas.js"></script>
    <script src="~/Scripts/Catalogos/modelo.js"></script>
    <script src="~/Scripts/select2.full.min.js"></script>

    <!--DATATABLE CATEGORIA-->
    <script>
        $("#small-modal").draggable({
            handle: ".modal-header"
        });

        //LLENANDO EL DATATABLE CRUD
        $(document).ready(function () {
            //DEFINIENDO EL DATATABLE
            $("#Table").DataTable({
                ajax: {
                    url: "/CategoriasMenu/GetData", //URL DE LA UBICACION DEL METODO
                    type: "GET", //TIPO DE ACCION
                    dataType: "JSON" //TIPO DE DATO A RECIBIR O ENVIAR
                },
                //DEFINIENDO LAS COLUMNAS A LLENAR
                columns: [
                    { data: "CodigoCategoriaMenu" },
                    { data: "DescripcionCategoriaMenu" },
                    {   //DEFINIENDO LOS BOTONES PARA EDITAR Y ELIMINAR POR MEDIO DE JS
                        data: "Id", "render": function (data) {
                            return "<a class='btn btn-success' onclick=CargarParcial('/CategoriasMenu/Edit/" + data + "')><i class='fa fa-pencil'></i></a>" +
                                "<a class='btn btn-danger' Style='margin-left: 3px' onclick=deleteAlert('/CategoriasMenu/Delete/'," + data + ")><i class='fa fa-trash'></i></a>"
                        }
                    }
                ],//FIN DE COLUMNAS
                //IDIOMA DE DATATABLE
                "language": {

                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",

                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                }//FIN IDIOMA DATATABLE
            });//FIN DECLARACION DEL DATATABLE
        });//FIN FUNCTION
    </script>
}